### GET doct
GET http://localhost:5094/api/Doctors

### GET doct
GET http://localhost:5094/api/Patients

### GET staff
GET http://localhost:5094/api/Staff

### Add staff
POST http://localhost:5094/api/Staff
content-type: application/json

{
    "StaffName": "Test",
    "StaffPhoneNo": "012341482",
    "StaffPass": "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
    "StaffRole": "Receptionist",
    "StaffEmail": "test@test.com"
}

### add patients
POST http://localhost:5094/api/Patients
Content-Type: application/json

{
    "ICNumber": "012312",
    "PatientName": "terse",
    "PatientPhoneNo": "123124124",
    "PatientEmail": "test@test",
    "PatientDOB": "2024-03-23T14:30:15.1234567Z",
    "PatientAddress": "rumah dia",
    "PatientGender": "L"
}

### add apoinment
GET http://localhost:5094/api/Appointments

### add apoinment
POST http://localhost:5094/api/Appointments
content-type: application/json

{
    "AppointmentDateTime": "2024-03-24T10:30:00",
    "AppointmentReason": "Routine Checkup",
    "AppointmentStatus": "Scheduled",
    "AppointmentType": "Consultation",
    "DoctorID": 1,
    "icNumber": "012312"
}